const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const packageJson = require(path.join(root, 'package.json'));
const { packageComponents } = require(path.join(root, 'metadata', 'components'));

function createEntrySource() {
  const components = packageComponents.map((component) => `    '${component}',`).join('\n');
  return [
    '/* This file is generated by scripts/generate-entry.js. Do not edit manually. */',
    'module.exports = {',
    `  version: '${packageJson.version}',`,
    "  visualConfig: require('./common/utils/visual-config'),",
    '  components: [',
    components,
    '  ],',
    '};',
    '',
  ].join('\n');
}

if (require.main === module) {
  fs.writeFileSync(path.join(root, 'index.js'), createEntrySource());
  console.log(`Generated index.js for ${packageComponents.length} components.`);
}

module.exports = { createEntrySource };
