const assert = require('assert'); const fs = require('fs'); const path = require('path'); const vm = require('vm');
const root=path.resolve(__dirname,'..'); const source=fs.readFileSync(path.join(root,'list/list.js'),'utf8'); const wxml=fs.readFileSync(path.join(root,'list/list.wxml'),'utf8'); const preview=fs.readFileSync(path.join(root,'preview/app.js'),'utf8'); const contract=fs.readFileSync(path.join(root,'docs/components/LIST.md'),'utf8'); let definition;
vm.runInNewContext(source,{Component(value){definition=value;},require(){return{};},Number,JSON,Math,console}); assert(definition); assert.strictEqual(Object.keys(definition.properties).length,31);
assert(wxml.includes('<pui-cell')&&wxml.includes('<pui-badge')&&wxml.includes('<pui-loading')&&wxml.includes('<pui-empty')&&wxml.includes('<pui-button'));
assert(contract.includes('error > loading > empty')&&contract.includes('error > loading > finished > ready')); assert(preview.includes('function listShowcase(props, demo)'));
function create(overrides={}){const defaults=Object.fromEntries(Object.entries(definition.properties).map(([k,v])=>[k,v.value])); const events=[];const instance={properties:{...defaults,...overrides},data:{...definition.data},_ready:true,getColorSchemeClass(){return'pui-theme-light';},setData(p){Object.assign(this.data,p);},triggerEvent(n,d){events.push({n,d});}};Object.assign(instance,definition.methods);instance.syncState();return{instance,events};}
const empty=create({error:true,loading:true});assert.strictEqual(empty.instance.data.stateType,'error');assert.strictEqual(empty.instance.data.footerState,'error');empty.instance.onFooterTap();assert.strictEqual(empty.events.at(-1).n,'retry');
const content=create({items:[{title:'零',value:0,badge:0}],loading:true,error:true});assert.strictEqual(content.instance.data.stateType,'content');assert.strictEqual(content.instance.data.footerState,'error');assert.strictEqual(content.instance.data.normalizedItems[0].value,0);assert.strictEqual(content.instance.data.normalizedItems[0].badgeVisible,true);
const finished=create({items:[{title:'A'}],finished:true});assert.strictEqual(finished.instance.requestFooter('tap'),false);const disabled=create({items:[{title:'A'}],disabled:true});assert.strictEqual(disabled.instance.onItemTap({currentTarget:{dataset:{index:0}}}),false);
console.log('List contract tests passed.');
