'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const root = path.resolve(__dirname, '..');
const chartData = require(path.join(root, 'common/utils/chart-data'));
const source = fs.readFileSync(path.join(root, 'waffle/waffle.js'), 'utf8');
let definition = null;
vm.runInNewContext(source, {
  console, isFinite, clearTimeout, setTimeout,
  require(request) { return request.includes('chart-data') ? chartData : {}; },
  Component(value) { definition = value; },
}, { filename: 'waffle/waffle.js' });
assert(definition, 'Waffle component definition must be registered');
function create(overrides) {
  const defaults = {};
  Object.keys(definition.properties).forEach((key) => { defaults[key] = definition.properties[key].value; });
  const instance = { data: Object.assign({}, definition.data, defaults, overrides || {}), getColorSchemeClass() { return 'pui-theme--light'; }, setData(patch) { Object.assign(this.data, patch); } };
  Object.keys(definition.methods).forEach((key) => { instance[key] = definition.methods[key]; });
  definition.lifetimes.attached.call(instance);
  return instance;
}
assert.deepStrictEqual(Object.keys(definition.properties).sort(), ['animated', 'ariaLabel', 'columns', 'duration', 'groupColumns', 'items', 'maxCells', 'reduceMotion', 'shape', 'showLegend', 'showValue', 'size', 'unit']);
assert.strictEqual(definition.properties.animated.value, true);
assert.strictEqual(definition.properties.duration.value, 500);
assert.strictEqual(typeof definition.methods.replay, 'function');
assert(source.includes('function resetCommitted()') && source.includes('this.data.reduceMotion ? 0 : 32'), 'Waffle replay must commit a reset frame before re-entering');
const regular = create({ items: [{ key: 'all', label: '组件', segments: [{ key: 'old', label: '已有', value: 8, theme: 'neutral' }, { key: 'new', label: '新增', value: 2, theme: 'violet' }] }] });
assert.strictEqual(regular.data.effectiveUnit, '1');
assert.strictEqual(regular.data.chartItems[0].cells.length, 10);
assert(regular.data.chartItems[0].cells[0].style.includes('--pui-waffle-opacity:1;'));
assert(regular.data.chartItems[0].cells[7].style.includes('--pui-waffle-opacity:0.28;'));
assert(regular.data.chartItems[0].cells[8].style.includes('--pui-waffle-opacity:1;'));
assert(regular.data.chartItems[0].cells[8].style.includes('--pui-chart-delay:112ms;'));
const grouped = create({ items: [{ key: 'all', label: '组件', value: 9, theme: 'violet' }], columns: 6, groupColumns: 3 });
assert.strictEqual(grouped.data.chartItems[0].cells[3].groupStart, true);
assert.strictEqual(grouped.data.chartItems[0].cells[6].groupStart, false);
const scaled = create({ items: [{ key: 'large', label: '测试', value: 486, theme: 'teal' }], maxCells: 80, columns: 30, shape: 'bad', reduceMotion: true });
assert.strictEqual(scaled.data.effectiveUnit, '7');
assert.strictEqual(scaled.data.scaled, true);
assert.strictEqual(scaled.data.chartItems[0].cells.length, 70);
assert(scaled.data.rootStyle.includes('--pui-waffle-columns:12'));
assert(scaled.data.rootClass.includes('pui-waffle--rounded'));
assert(scaled.data.rootStyle.includes('1ms'));
assert(scaled.data.semanticLabel.includes('每格代表 7'));
const wxml = fs.readFileSync(path.join(root, 'waffle/waffle.wxml'), 'utf8');
const wxss = fs.readFileSync(path.join(root, 'waffle/waffle.wxss'), 'utf8');
const theme = fs.readFileSync(path.join(root, 'common/style/theme.wxss'), 'utf8');
const preview = fs.readFileSync(path.join(root, 'preview/app.js'), 'utf8');
const previewStyles = fs.readFileSync(path.join(root, 'preview/styles.css'), 'utf8');
const contract = fs.readFileSync(path.join(root, 'docs/components/WAFFLE.md'), 'utf8');
const metadata = require(path.join(root, 'metadata/components'));
const miniPage = fs.readFileSync(path.join(root, 'miniprogram/pages/components/waffle/index.wxml'), 'utf8');
assert(wxml.includes('1 格 = {{effectiveUnit}}'));
assert(wxml.includes('wx:if="{{scaled}}"'));
assert(!wxml.includes('showValue && scaled'));
assert(wxml.includes('pui-waffle__cell--group-start'));
assert(!source.includes('triggerEvent('));
assert(!wxml.includes('<canvas'));
assert(wxss.includes('box-shadow:inset'));
assert(wxss.includes('background:var(--pui-chart-cell-gradient'));
assert(wxss.includes('pui-waffle--entered'));
assert(!wxss.includes('var(--pui-shadow'));
assert(theme.includes('--pui-chart-cell-radius: 8rpx'));
assert(theme.includes('--pui-chart-cell-radius: 12rpx'));
assert(metadata.packageComponents.includes('waffle'));
assert.deepStrictEqual(metadata.apiProps.waffle, ['items', 'columns', 'groupColumns', 'shape', 'size', 'unit', 'maxCells', 'showValue', 'showLegend', 'animated', 'duration', 'ariaLabel', 'reduceMotion']);
assert.strictEqual((metadata.apiEvents.waffle || []).length, 0);
assert.strictEqual((metadata.apiSlots.waffle || []).length, 0);
assert.deepStrictEqual((metadata.apiMethods.waffle || []).map((item) => item.name), ['replay()']);
assert(preview.includes('function waffleShowcase(props, demo)'));
assert(!preview.includes("props.showValue !== false && effectiveUnit > requestedUnit ? `<small class=\"pui-waffle-preview__unit\""));
assert(preview.includes("is-group-start"));
assert(preview.includes("chartPreviewProps('waffle', props, demo)") && preview.includes("chartDataToggleButton('waffle', demo)"), 'H5 Waffle must expose a large cell-count change owned by the parent demo');
assert(previewStyles.includes('.pui-waffle-preview'));
assert(previewStyles.includes('.pui-waffle-preview.is-entered'));
assert(preview.includes("type === 'chart-replay'") && preview.includes('replayChartEntrancePreviewRuntime(props)'), 'H5 chart replay action must use the shared committed-reset runtime');
assert(previewStyles.includes('.pui-waffle-preview.is-replay-reset .pui-waffle-preview__cell'), 'Waffle reset frame must disable reverse transition');
assert(contract.includes('effectiveUnit'));
assert(contract.includes('`animated'));
assert(contract.includes('`replay()`'));
assert(miniPage.includes('<pui-waffle'));
assert(miniPage.includes('bind:click="onReplay"'));
assert(miniPage.includes('bind:click="onToggleWaffleData"') && !miniPage.includes('新增 +1'), 'Waffle page must replace the imperceptible +1 demo with a high-variance data toggle');
console.log('Waffle contract tests passed.');
